### ISSUE TITLE
Error after fresh install

### ISSUE THREAD

**Issue by robert4os** [flomader/timereporter#6]
Hello Florian,

I have installed the extension for the first time on Edge and it generates the following errors:
![image](https://user-images.githubusercontent.com/1668298/104456872-999d7800-55a9-11eb-9704-959f34173204.png)

The problem is mitigated when checking and saving the TimeReporter Settings, so some issue with the default seetings object.

Thank you for the great tool!!!

Best regards,
Robert

**Comment by flomader** [comment]
Thanks for reporting this issue.
It has been fixed with release 1.1.2. 
Currently in the process of publishing to the Marketplace.
