### ISSUE TITLE
Timereporter not working due to new URL

### ISSUE THREAD

**Issue by mfussthaler** [flomader/timereporter#7]
Seems that the addon doesn't work since the URL was changed to https://msvacation.microsoft.com/.

**Comment by mfussthaler** [comment]
Version 1.1.3 still doesn't populate work time. There is also a new column since 01/22.

**Comment by flomader** [comment]
Do you see any values inserted but you cannot submit? On my machine the values are generated and inserted and I can save them. I currently cannot test submit because of LOA, though. Populating the new column (Home Office) is not available yet.

**Comment by mfussthaler** [comment]
The timereporter icon becomes colored when entering the work time submission page with 1.1.3. But left- & right-click result in the same action and open the context menu. No values are inserted, tested with Edge Version 97.0.1072.76 (Official build) (64-bit).

**Comment by flomader** [comment]
Verified as bug. Thanks for reporting. 
The issue happens when the url is written all lowercase. Quick fix to get it working: change "wtt" in the URL to "WTT". I will make a fix but it will usually take a few days to update in the marketplace.

**Comment by flomader** [comment]
fixed in 1.1.4
